import type { Report } from "@/hooks/use-reports";

export function exportReportAsHtml(report: Report) {
  const reportData = report.report_data as Record<string, unknown> | null;
  if (!reportData) return;

  const data = reportData as {
    title?: string;
    summary?: string;
    stats?: Array<{ label: string; value: string | number; change?: string }>;
    insights?: string[];
    tables?: Array<{ title: string; headers: string[]; rows: (string | number)[][] }>;
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${report.title} - DataViz AI Report</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0a0e1a;
      color: #e2e8f0;
      line-height: 1.6;
      padding: 2rem;
    }
    .container { max-width: 1000px; margin: 0 auto; }
    h1 {
      font-size: 2rem;
      background: linear-gradient(135deg, #4a90e2, #36bfb1);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 0.5rem;
    }
    .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 2rem; }
    .card {
      background: rgba(15, 23, 42, 0.7);
      border: 1px solid rgba(74, 144, 226, 0.12);
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      backdrop-filter: blur(16px);
    }
    .card h2 {
      font-size: 1.1rem;
      margin-bottom: 1rem;
      background: linear-gradient(135deg, #4a90e2, #36bfb1);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
    .stat {
      background: rgba(15, 23, 42, 0.7);
      border: 1px solid rgba(74, 144, 226, 0.12);
      border-radius: 12px;
      padding: 1.25rem;
    }
    .stat .label { color: #64748b; font-size: 0.875rem; }
    .stat .value { font-size: 1.5rem; font-weight: 700; margin-top: 0.25rem; }
    .stat .change { font-size: 0.75rem; margin-top: 0.25rem; color: #36bfb1; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid rgba(74, 144, 226, 0.1); }
    th { color: #64748b; font-size: 0.875rem; font-weight: 600; }
    .insight-list { list-style: none; }
    .insight-list li {
      display: flex;
      gap: 0.75rem;
      margin-bottom: 0.75rem;
      font-size: 0.9rem;
      color: #94a3b8;
    }
    .insight-num {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 24px;
      height: 24px;
      border-radius: 50%;
      background: linear-gradient(135deg, #4a90e2, #36bfb1);
      color: white;
      font-size: 10px;
      font-weight: 700;
      flex-shrink: 0;
    }
    .footer { text-align: center; color: #475569; font-size: 0.75rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid rgba(74, 144, 226, 0.1); }
  </style>
</head>
<body>
  <div class="container">
    <h1>${report.title}</h1>
    <p class="meta">Generated on ${new Date(report.created_at).toLocaleString()} | File: ${report.file_name}</p>

    ${data.summary ? `<div class="card"><h2>Summary</h2><p style="color:#94a3b8">${data.summary}</p></div>` : ""}

    ${data.stats && data.stats.length > 0 ? `
    <div class="stats-grid">
      ${data.stats.map((s) => `
        <div class="stat">
          <div class="label">${s.label}</div>
          <div class="value">${s.value}</div>
          ${s.change ? `<div class="change">${s.change}</div>` : ""}
        </div>
      `).join("")}
    </div>` : ""}

    ${data.tables ? data.tables.map((t) => `
    <div class="card">
      <h2>${t.title}</h2>
      <table>
        <thead><tr>${t.headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
        <tbody>${t.rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody>
      </table>
    </div>`).join("") : ""}

    ${data.insights && data.insights.length > 0 ? `
    <div class="card">
      <h2>Key Insights</h2>
      <ul class="insight-list">
        ${data.insights.map((ins, i) => `
          <li><span class="insight-num">${i + 1}</span><span>${ins}</span></li>
        `).join("")}
      </ul>
    </div>` : ""}

    <div class="footer">Generated by DataViz AI</div>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.title.replace(/\s+/g, "_")}_report.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
